services:
  keepalive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keepalive
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
